# @package _global_

defaults:
  - _self_
  - data: blip # choose datamodule with `test_dataloader()` for evaluation
  - model: blip
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ./logs/train/runs/2023-09-09_10-53-01/checkpoints/epoch_012.ckpt
