# @package _global_

defaults:
  - _self_
  - data: blip # choose datamodule with `test_dataloader()` for evaluation
  - model: blip
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/user/captioning/lightning-hydra-template/logs/train/runs/2023-09-06_21-50-45/checkpoints/epoch_002.ckpt
