_target_: src.models.blip_module.BlipModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 50

net:
  _target_: Blip.model.model
  pretrain: "Salesforce/blip-image-captioning-base"
  
