_target_: src.models.blip_module.BlipModule

top_k: 50
top_p: 1.0

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  momentum: 0.9
  lr: 0.000001
  weight_decay: 0.05

scheduler:
  _target_: cosine_annealing_warmup.CosineAnnealingWarmupRestarts
  _partial_: true
  first_cycle_steps: 12e+3
  cycle_mult: 1.0
  max_lr: 1e-5
  min_lr: 1e-8
  warmup_steps: 4e+3
  gamma: 0.9

net:
  _target_: Blip.model.model
  pretrain: "Salesforce/blip-image-captioning-base"
  train_module: ["crossattention", "text_decoder.cls"]
  lora_module: [vision_model, attention.self.query, attention.self.value]
  
  
        
