_target_: src.models.blip_module.BlipModule

top_k: 0
top_p: 0.9

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.000001
  weight_decay: 0.05

scheduler:
  _target_: cosine_annealing_warmup.CosineAnnealingWarmupRestarts
  _partial_: true
  first_cycle_steps: 9e+3
  cycle_mult: 1.0
  max_lr: 1e-4
  min_lr: 1e-8
  warmup_steps: 3e+3
  gamma: 0.75

net:
  _target_: Blip.model.model
  pretrain: "Salesforce/blip2-opt-2.7b"
  train_module: [qformer]
  lora_module: [v_proj, q_proj]
  
